import React, {useState,useRef,useEffect} from 'react';
import {SquaresFour,FileText,ShareNetwork,ArrowUpRight,BookOpen,Palette,Users,Code} from '@phosphor-icons/react';
const home='https://ibloud.github.io/pixie-device-stewardship/';
const repo='https://github.com/ibloud/pixie-device-stewardship';
const r=(name,url,by,description,why,access='No account needed to read',source='Awesome ATProto')=>({name,url,by,description,why,access,source});
const docs=r('AT Protocol documentation','https://atproto.com/','AT Protocol contributors','The official documentation for the open protocol behind the Atmosphere.','Understand identity, public records and how apps work together.');
const standard=r('Standard.site introduction','https://standard.site/docs/introduction/','Standard.site community','Shared publication and document schemas for writing on the open social web.','Learn how to connect published writing through AT Protocol records.','No account needed to read','Loptr Lab addition');
const smoke=r('Smoke Signal','https://smokesignal.events/','Smoke Signal contributors','Events and RSVP management built on AT Protocol.','Organize a workshop or playtest in a separate community service.','Account access needed to create events or RSVP');
const resources={
 Learn:[docs,r('AT Protocol glossary','https://atproto.com/guides/glossary','AT Protocol contributors','A reference for handles, DIDs, repositories and other protocol terms.','Translate unfamiliar vocabulary before choosing a tool.'),r('A perspective on decentralization','https://dustycloud.org/blog/how-decentralized-is-bluesky/','Christine Lemmer-Webber','An independent critique of Bluesky’s architecture.','Explore trade-offs alongside official documentation. A dated analysis, not current product guidance.')],
 Create:[r('Streamplace','https://stream.place/','Streamplace contributors','Explore live video for creative sessions and playtests.','Find a streaming pathway for your creative practice.','Explore publicly; broadcasting is a separate choice','Loptr Lab addition'),r('PinkSea','https://pinksea.art/','PinkSea / Shinon labs contributors','An AT Protocol drawing and art community.','Explore an art-focused use of the shared network.','Account access needed to publish'),smoke],
 Publish:[standard,docs,r('Linkat','https://linkat.blue/','Linkat / mkizka contributors','Create a link-in-bio page using your Bluesky identity.','Give your creative projects a shared destination.','Account access needed to create your page'),r('Bluesky website comments','https://github.com/czue/bluesky-comments','Cory Zue and contributors','Display a Bluesky discussion on a website.','Connect a page with an existing public discussion. Requires developer setup.'),r('OpenPost','https://github.com/getopenpost/openpost','OpenPost contributors','Open-source tooling for creating and scheduling social posts.','Explore hosted or self-hosted publishing workflows.','Connecting social accounts needs separate authorization')],
 Connect:[r('BookHive','https://bookhive.buzz/','BookHive / nperez0111 and contributors','A community for tracking and discovering books.','See a shared identity supporting a community beyond a social timeline.','Account access needed for reading activity'),smoke,r('Bluesky labeler directory','https://blue.mackuba.eu/labellers/','Mackuba','A community directory of labeler services.','Explore moderation choices; inspect each service’s policies before subscribing.')],
 Build:[r('PDSls','https://pdsls.dev/','PDSls contributors','A browser for AT Protocol records.','Inspect public records while learning or debugging.','Public browsing and authorized record edits are separate'),r('Bluesky lexicon examples','https://github.com/bluesky-social/atproto/tree/main/lexicons/app/bsky','Bluesky and AT Protocol contributors','The schemas defining Bluesky records and services.','Use maintained examples to design interoperable features.'),r('ATFile','https://github.com/ziodotsh/atfile','ziodotsh and contributors','A file-storage experiment using AT Protocol records.','Study a developer reference. Public records are not private storage.','Do not use public records for private files'),r('Linkat lexicon examples','https://github.com/mkizka/linkat/tree/main/lexicons/blue/linkat','mkizka and contributors','The schemas behind shared link pages.','Study a small application’s record structure.')]
};
const icons={Learn:BookOpen,Create:Palette,Publish:FileText,Connect:Users,Build:Code};
function Resource({item,category}){const Icon=item.name.includes('Protocol')?ShareNetwork:icons[category];return <article className="resource-row"><div className="resource-copy"><span className="resource-icon"><Icon size={34} weight="fill" aria-hidden="true"/></span><div><h3>{item.name}</h3><p>{item.description}</p><p className="credit">By {item.by}</p></div></div><div className="resource-why"><span>Why useful</span><p>{item.why}</p></div><div className="resource-action"><span className="access">{item.access}</span><a href={item.url}>Open {item.url.includes('github.com')?'source':'guide'} <ArrowUpRight size={16} aria-hidden="true"/></a><details><summary>Source &amp; check</summary><p>{item.source}. Destination retrieved October 7, 2026.</p></details></div></article>}
export function App(){
 const [category,setCategory]=useState('Learn');
 const [fromMadeSick,setFromMadeSick]=useState(false);
 const ref=useRef(null);
 const resultsRef=useRef(null);
 useEffect(()=>{setFromMadeSick(new URLSearchParams(window.location.search).get('from')==='made-sick');},[]);
 const count=resources[category].length;
 const focusIdentity=()=>{ref.current?.focus();ref.current?.scrollIntoView({behavior:'auto',block:'start'});};
 const goCreate=()=>{setCategory('Create');requestAnimationFrame(()=>{resultsRef.current?.focus();resultsRef.current?.scrollIntoView({behavior:'auto',block:'start'});});};
 return <><a className="skip-link" href="#main">Skip to the guide</a><div className="page">
 <header><a className="brand" href="https://ibloud.github.io/ecosystem/"><SquaresFour size={29} weight="fill" aria-hidden="true"/><span><strong>LOPTR LAB</strong><small>Atmosphere field guide</small></span></a><nav aria-label="Field guide navigation"><a href="#identity">Identity</a><a href="#pathways">Paths</a><a href="https://ibloud.github.io/ecosystem/">Our projects</a></nav><a className="repo-button" href={repo}>Open repository <ArrowUpRight size={15} aria-hidden="true"/></a></header>
 <main id="main"><section className="hero"><div><p className="eyebrow">Loptr Lab field guide</p><h1>Getting to Know<br/><em>the Atmosphere</em></h1><p className="hero-description">{fromMadeSick?"You came from Made Sick. Here’s how the account you just saw works.":"The Atmosphere is a network of independent apps. Your account connects them; you choose what to use, what to share, and how you participate."}</p><button className="primary" onClick={focusIdentity}>Understand the account</button></div><figure><img src="assets/atmosphere-orbit.jpg" alt=""/><figcaption>Different apps. A shared identity.<br/>You stay in control.</figcaption></figure></section>
 <section className="identity" aria-labelledby="identity"><h2 id="identity" ref={ref} tabIndex={-1}>One account. A different home.</h2>
 <p><strong>@made-sick.org</strong> is our account. On October 7, 2026, its public identity record changed to point to <strong>Eurosky</strong> as its account server. Its underlying identity stayed <code className="did">did:plc:o6kuv3yieti2vqrb7ckmd5vg</code>. Followers do not need to follow a new account when the same identity moves.</p>
 <p><a href="https://plc.directory/did:plc:o6kuv3yieti2vqrb7ckmd5vg">See the public identity record <ArrowUpRight size={16} aria-hidden="true"/></a>. Eurosky is operated by Stichting Modal, a Netherlands foundation, and describes EU hosting. The server address is <code>https://eurosky.social</code>. Account sign-in and participant publishing are still being checked while the migration settles.</p>
 <dl className="identity-terms"><div><dt>Handle</dt><dd>The readable name people use to find you: @made-sick.org.</dd></div><div><dt>DID</dt><dd>The stable identifier that lets services recognize the same account after a move.</dd></div><div><dt>Personal Data Server (PDS)</dt><dd>The provider hosting your account and its public records. You can choose a different provider.</dd></div><div><dt>AppView</dt><dd>A service that gathers public records so an app can show feeds or search. It is separate from your account server.</dd></div></dl>
 <p>A server move does not make public posts private or keep every copy in the EU. Each app has its own permissions and policies. Read those before authorizing access; keep private health records, credentials and confidential files out of public records.</p>
 <a href="https://github.com/ibloud/ibloud.github.io/blob/main/docs/ECOSYSTEM_ARCHITECTURE.md#made-sick-account-hosting--7-october-2026">Account hosting evidence and policy baseline <ArrowUpRight size={16} aria-hidden="true"/></a>
 </section>
 <section className="pathways" aria-labelledby="pathways"><h2 id="pathways">Your next step</h2><p>Explore guides and resources to learn, create, publish, connect, or build.<br/>Choose a path that fits your curiosity. You can always come back.</p><div className="categories" aria-label="Choose a resource path">{Object.keys(resources).map(name=><button key={name} aria-pressed={category===name} onClick={()=>setCategory(name)}>{name}</button>)}</div></section>
 <section className="results" aria-labelledby="results-title"><h2 id="results-title" ref={resultsRef} tabIndex={-1}>{category==='Publish'?'Guides for publishing':category==='Learn'?'Understand the network':category==='Create'?'Make something of your own':category==='Connect'?'Find your community':'Build with shared records'}</h2><p className="results-description" role="status">{category==='Publish'?'These resources explain how publishing works in the open social web.':`${count} resources for this path. Visit the original creators to explore further.`}</p>{resources[category].slice(0,2).map(item=><Resource key={item.name} item={item} category={category}/>)}{count>2&&<details className="more" key={category}><summary>More for {category.toLowerCase()} <span>{count-2} resources</span></summary>{resources[category].slice(2).map(item=><Resource key={item.name} item={item} category={category}/>)}</details>}</section>
 <aside className="made-sick"><img src="assets/made-sick-icon.svg" alt="Made Sick icon"/><div><h2>{fromMadeSick?'Take your next step: Create':'From Made Sick to your own creative practice'}</h2><p>{fromMadeSick?'You’ve seen how the account connects the network. Explore art, live video and community events; opening a resource is your choice.':'Made Sick connects our public campaign and participation work. Continue here to explore tools for your creative practice, with PIXIE’s consent and stewardship principles.'}</p></div>{fromMadeSick?<button className="create-step" onClick={goCreate}>Explore Create <ArrowUpRight size={17} aria-hidden="true"/></button>:<a href="https://made-sick.org/">Explore Made Sick <ArrowUpRight size={17} aria-hidden="true"/></a>}</aside>
 <p className="boundary">These are independent community resources, not connected PIXIE services. Opening a link contacts that destination. This guide does not sign you in or publish anything.</p></main>
 <footer><p>Original resource collection by <a href="https://github.com/atblueprints/awesome-atproto">atblueprints and contributors</a>.<br/>A Loptr Lab field guide, built with PIXIE’s consent and device stewardship principles.<br/>Last checked October 7, 2026. Desktop browser verified; iPad Safari, VoiceOver and destination account flows not yet verified.<br/><a href={repo+'/blob/main/docs/atmosphere/README.md'}>Sources and community maintenance</a></p><strong>People over profit. Accessibility first.</strong></footer></div></>;
}
